In [1]:
"""
1. Perform the relevant text preprocessing steps on the dataset provided (use csv, library 
and text files all) and write your observations/reasons about the preprocessing you did. 
"""

'\n1. Perform the relevant text preprocessing steps on the dataset provided (use csv, library \nand text files all) and write your observations/reasons about the preprocessing you did. \n'

In [2]:
import nltk
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
nltk.download('brown')
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('movie_reviews')

[nltk_data] Downloading package brown to
[nltk_data]     C:\Users\kgliv\AppData\Roaming\nltk_data...
[nltk_data]   Package brown is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\kgliv\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\kgliv\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package movie_reviews to
[nltk_data]     C:\Users\kgliv\AppData\Roaming\nltk_data...
[nltk_data]   Package movie_reviews is already up-to-date!

True

### Preprocessing Pipeline

In [4]:
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer

def lower(text):
    return text.lower()

def remove_punct(text):
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'https?://\S+', '', text)
    return text

def tokenize(text):
    return word_tokenize(text)

def stop_words(tokens):
    stop_words = stopwords.words('english')
    tokens = [token for token in tokens if token not in stop_words and token.isalpha()]
    return tokens 

def stemming(tokens):
    stemmer = PorterStemmer()
    return [ stemmer.stem(token) for token in tokens ]

def lemmatizing(tokens):
    lemmatizer = WordNetLemmatizer()
    return [ lemmatizer.lemmatize(token) for token in tokens ]


def preprocessing(text):
    text = lower(text)
    text = remove_punct(text)
    tokens = word_tokenize(text)
    tokens = stop_words(tokens)
    tokens = stemming(tokens)
    tokens = lemmatizing(tokens)
    return ' '.join(tokens)

text = "This is sample text containing    impurity like https://abc.net  all of that punctuations,."
preprocessing(text)

'sampl text contain impur like httpsabcnet punctuat'

### Text file - sample.txt

In [5]:
with open("sample.txt", "r") as ptr:
    data = ptr.read()
    txt_df = pd.DataFrame(data.split('\n'), columns=["text"] )
txt_df

                                                text
0  Natural Language Processing (NLP) is a fascina...
1  It helps computers understand, interpret, and ...
2  I am learning NLP in 2026, and I really enjoy ...
3  Preprocessing is an important step because raw...
4  extra spaces, CAPITAL letters, and unnecessary...
5  For example, this sentence has     multiple sp...
6  It also contains numbers like 123 and special ...
7  Text preprocessing makes the data cleaner and ...
8  However, we should carefully decide which word...

In [6]:
txt_df['text'] = txt_df['text'].apply(preprocessing)
txt_df

                                                text
0  natur languag process nlp fascin field artific...
1  help comput understand interpret gener human l...
2              learn nlp realli enjoy work text data
3  preprocess import step raw text contain punctu...
4          extra space capit letter unnecessari word
5         exampl sentenc multipl space punctuat mark
6            also contain number like special symbol
7    text preprocess make data cleaner easier analyz
8          howev care decid word symbol inform remov

### CSV - sample.csv

In [7]:
csv_df = pd.read_csv("sample.csv")
csv_df

          Id                                            Comment      Topic
0     0x1aa9  Personally I have no idea what my IQ is. I’ve ...    Biology
1      0x25e  I'm skeptical. A heavier lid would be needed t...    Physics
2     0x1248  I think I have 100 cm of books on the subject....    Biology
3      0x2b9  Is chemistry hard in uni. Ive read somewhere t...  Chemistry
4     0x24af  In addition to the other comment, you can crit...    Physics
...      ...                                                ...        ...
1581  0x22bf  I’m not really denying your intent. I’m a) dou...  Chemistry
1582  0x1f4a  i really empathize with your compassion for bu...    Biology
1583  0x27b7  If you want to keep it for more than 2 weeks, ...  Chemistry
1584  0x2066  Same here. I’m in nursing school so I only hav...    Biology
1585   0x6d6  The video basically says read a pop-sci book a...    Physics

[1586 rows x 3 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
csv_df['Topic'] = encoder.fit_transform(csv_df['Topic'])

csv_df['Comment'] = csv_df['Comment'].apply(preprocessing)
csv_df

          Id                                            Comment  Topic
0     0x1aa9  person idea iq ive never test howev test outda...      0
1      0x25e  im skeptic heavier lid would need build pressu...      2
2     0x1248  think cm book subject tldr problem conscious u...      0
3      0x2b9  chemistri hard uni ive read somewher hardest d...      1
4     0x24af  addit comment critic theori without check lot ...      2
...      ...                                                ...    ...
1581  0x22bf  im realli deni intent im doubt third comment i...      1
1582  0x1f4a  realli empath compass bug entomolog realli int...      0
1583  0x27b7  want keep week would go someth like l also wan...      1
1584  0x2066  im nurs school basic understand thing like see...      0
1585   0x6d6  video basic say read popsci book want go quant...      2

[1586 rows x 3 columns]

### Library - movie_reviews

In [9]:
from nltk.corpus import movie_reviews

lib_data = np.array([ (movie_reviews.raw(fileid), movie_reviews.categories(fileid)[0] ) for fileid in movie_reviews.fileids() ])
lib_df = pd.DataFrame(lib_data, columns = ["text", "label"])
lib_df.head()

                                                text label
0  plot : two teen couples go to a church party ,...   neg
1  the happy bastard's quick movie review \ndamn ...   neg
2  it is movies like these that make a jaded movi...   neg
3   " quest for camelot " is warner bros . ' firs...   neg
4  synopsis : a mentally unstable man undergoing ...   neg

In [10]:
lib_df["text"] = lib_df["text"].apply(preprocessing)
lib_df.head()

                                                text label
0  plot two teen coupl go church parti drink driv...   neg
1  happi bastard quick movi review damn bug got h...   neg
2  movi like make jade movi viewer thank invent t...   neg
3  quest camelot warner bro first featurelength f...   neg
4  synopsi mental unstabl man undergo psychothera...   neg

### *_Observation:_* I have tried with approach read then convert it in dataframe then apply function preprocessing on text. All of three we have to generalize in dataframe just reading is different step in all