In [1]:
"""
2. Implement a lemmatizer using the WordNet and compare its output with stemming. Use 
the Gutenberg Corpus.   
"""

'\n2. Implement a lemmatizer using the WordNet and compare its output with stemming. Use \nthe Gutenberg Corpus.   \n'

In [2]:
import numpy as np
import pandas as pd 
import re, nltk

In [3]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer

def lower(text):
    return text.lower()

def remove_punct(text):
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'https?://\S+', '', text)
    return text

def tokenize(text):
    return word_tokenize(text)

def stop_words(tokens):
    stop_words = stopwords.words('english')
    tokens = [token for token in tokens if token not in stop_words and token.isalpha()]
    return tokens 

def stemming(tokens):
    stemmer = PorterStemmer()
    return [ stemmer.stem(token) for token in tokens ]

def lemmatizing(tokens):
    lemmatizer = WordNetLemmatizer()
    return [ lemmatizer.lemmatize(token) for token in tokens ]


def preprocessing_stemming(text):
    text = lower(text)
    text = remove_punct(text)
    tokens = word_tokenize(text)
    tokens = stop_words(tokens)
    tokens = stemming(tokens)
    return ' '.join(tokens)

def preprocessing_lemmatizing(text):
    text = lower(text)
    text = remove_punct(text)
    tokens = word_tokenize(text)
    tokens = stop_words(tokens)
    tokens = lemmatizing(tokens)
    return ' '.join(tokens)

In [4]:
nltk.download('gutenberg')
from nltk.corpus import gutenberg

data = [ gutenberg.raw(fileid) for fileid in gutenberg.fileids() ]
df = pd.DataFrame(data, columns = ["text"])
df

[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\kgliv\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!

                                                 text
0   [Emma by Jane Austen 1816]\n\nVOLUME I\n\nCHAP...
1   [Persuasion by Jane Austen 1818]\n\n\nChapter ...
2   [Sense and Sensibility by Jane Austen 1811]\n\...
3   [The King James Bible]\n\nThe Old Testament of...
4   [Poems by William Blake 1789]\n\n \nSONGS OF I...
5   [Stories to Tell to Children by Sara Cone Brya...
6   [The Adventures of Buster Bear by Thornton W. ...
7   [Alice's Adventures in Wonderland by Lewis Car...
8   [The Ball and The Cross by G.K. Chesterton 190...
9   [The Wisdom of Father Brown by G. K. Chesterto...
10  [The Man Who Was Thursday by G. K. Chesterton ...
11  [The Parent's Assistant, by Maria Edgeworth]\r...
12  [Moby Dick by Herman Melville 1851]\r\n\r\n\r\...
13  [Paradise Lost by John Milton 1667] \n \n \nBo...
14  [The Tragedie of Julius Caesar by William Shak...
15  [The Tragedie of Hamlet by William Shakespeare...
16  [The Tragedie of Macbeth by William Shakespear...
17  [Leaves of Grass by Walt Whitman 1855]\n\n\nCo...

### Lemmatizing

In [5]:
# Lemmatizing
df['text'] = df['text'].apply(preprocessing_lemmatizing)
df

                                                 text
0   emma jane austen volume chapter emma woodhouse...
1   persuasion jane austen chapter sir walter elli...
2   sense sensibility jane austen chapter family d...
3   king james bible old testament king james bibl...
4   poem william blake song innocence experience b...
5   story tell child sara cone bryant two little r...
6   adventure buster bear thornton w burgess buste...
7   alices adventure wonderland lewis carroll chap...
8   ball cross gk chesterton discussion somewhat a...
9   wisdom father brown g k chesterton absence mr ...
10  man thursday g k chesterton edmund clerihew be...
11  parent assistant maria edgeworth orphan near r...
12  moby dick herman melville etymology supplied l...
13  paradise lost john milton book man first disob...
14  tragedie julius caesar william shakespeare act...
15  tragedie hamlet william shakespeare actus prim...
16  tragedie macbeth william shakespeare actus pri...
17  leaf grass walt whitman come said soul verse b...

### Stemming

In [6]:
# Stemming
df['text'] = df['text'].apply(preprocessing_stemming)
df

                                                 text
0   emma jane austen volum chapter emma woodhous h...
1   persuas jane austen chapter sir walter elliot ...
2   sens sensibl jane austen chapter famili dashwo...
3   king jame bibl old testament king jame bibl fi...
4   poem william blake song innoc experi book thel...
5   stori tell child sara cone bryant two littl ri...
6   adventur buster bear thornton w burgess buster...
7   alic adventur wonderland lewi carrol chapter r...
8   ball cross gk chesterton discuss somewhat air ...
9   wisdom father brown g k chesterton absenc mr g...
10  man thursday g k chesterton edmund clerihew be...
11  parent assist maria edgeworth orphan near ruin...
12  mobi dick herman melvil etymolog suppli late c...
13  paradis lost john milton book man first disobe...
14  tragedi juliu caesar william shakespear actu p...
15  tragedi hamlet william shakespear actu primu s...
16  tragedi macbeth william shakespear actu primu ...
17  leaf grass walt whitman come said soul vers bo...